### ISSUE TITLE
Slack Notifications

### ISSUE THREAD

**Issue by charnjit1234** [microscaling/microbadger#31]
Unable to send test notification to Slack, I added the webhook URL clicked 'Test' and it says 'Notification Sent' but nothing appears in the channel. I think this is due to the curl request as when I do it manually using the same web-hook URL it works. The curl request i used is:
`curl -X POST --data-urlencode "payload={\"text\":\"Hi, it's MicroBadger, sending you a test notification for alpine https://microbadger.com/images/alpine\",\"new_tags\":[],\"image_name\":\"alpine\",\"changed_tags\":[],\"deleted_tags\":[]}" https://hooks.slack.com/services/${WEBHOOK_URL}`

**Comment by rossf7** [comment]
Thanks for reporting this. The problem was the notifier component that sends the webhook notifications wasn't running. It was stopped during some emergency maintenance that was needed on our k8s cluster.

Its now running so this is fixed but please reopen if you still have problems with notifications. Sorry for any inconvenience caused.
